# RESTful API
server:
  # Server mode: release, debug, test;
  # Default: release
  mode: debug
  # Enable server health check or not，if enabled, will install /healthz router;
  # Default: true
  healthz: true
  # Option values: secure, nocache, cors, dump, options.
  # Default: ""
  middlewares:
    - secure
    - nocache
    - cors
  # Self ping check after server start;
  # Default: 3
  max-ping-count: 3

# HTTP
insecure:
  # Default: 127.0.0.1
  bind-address: 127.0.0.1
  # Default: 8080
  bind-port: 8080

# HTTPS
secure:
  # Default: 0.0.0.0
  bind-address: 0.0.0.0
  # If 0, means disable https;
  # Default: 8443
  bind-port: 8443
  tls:
    # X509 cert file, if null, will not enable https;
    # Default: ""
    cert-file: ./configs/cert/cert.pem
    # Cert key file;
    # Default: ""
    key-file: ./configs/cert/key.pem

# MySQL
mysql:
  # Default: 127.0.0.1:3306
  host: 127.0.0.1:3306
  # Default: ""
  username: "root"
  # Default: ""
  password: "123456"
  # Default: ""
  database: "gobackend"
  # Default: 100
  max-idle-connections: 100
  # Default: 100
  max-open-connections: 100
  # Default: 120(s)
  max-connection-lifetime: 120
  # GORM log level: silent, error, warn, info;
  # Default: silent
  log-level: info
  # Auto migrate database or not.
  # It is not recommended to open it in a production environment.
  # Default: false
  auto-migrate: true

log:
  # Logger name;
  # Default: ""
  name: apiserver
  # Values: debug, info, warn, error, dpanic, panic, fatal;
  # Default: info
  level: debug
  # Values: console, json;
  # Default: console
  format: console
  # Default: false
  disable-color: false
  # Caller will print filename, funcname, line number;
  # Default: false
  disable-caller: false
  # Stacktrace will print stack information above panic level;
  # Default: false
  disable-stacktrace: false
  # All log level messages will be writen to;
  # Default: stdout
  output-paths:
    - stdout
    - ./logs/gobackend-apiserver.log
  # Only log internal errors will be written to;
  # Default: stderr
  error-output-paths:
    - stderr
    - ./logs/gobackend-apiserver.error.log
  # Rotate log files or not;
  # Default: false
  enable-rotate: true
  # Maximum size in megabytes of the log file before it gets rotated,
  # if the value is 0, the log files will not be rotated.
  # Default: 100
  rotate-max-size: 100
  # Saved days, if 0, means no limit;
  # Default: 0
  rotate-max-age: 30
  # Saved count, if 0, means no limit;
  # Default: 0
  rotate-max-backups: 0
  # Use local time in log file name;
  # Default: true
  rotate-localtime: true
  # Gzip log files;
  # Default: false
  rotate-compress: false

feature:
  # If true, it will add router: /metrics;
  # Default: true
  enable-metrics: true
  # If true, it will add routers: /debug/pprof/[*];
  # Default: true
  profiling: true
  # If true, it will write operation logs to database.
  # Default: false
  operation-logging: true
